# version: '3.9'

services:
  zenn-local:
    build: .
    container_name: zenn-local
    ports:
      - "8080:8000"
    restart: always
    volumes:
      - "./:/usr/app"
    working_dir: /usr/app
    command: /bin/bash -c "npm install zenn-cli@latest && npx zenn preview"
    tty: true
    networks:
      - zenn-public

networks:
  zenn-public:
    driver: bridge
